// Generated by gencpp from file distance_converter/motorStatusResponse.msg
// DO NOT EDIT!


#ifndef DISTANCE_CONVERTER_MESSAGE_MOTORSTATUSRESPONSE_H
#define DISTANCE_CONVERTER_MESSAGE_MOTORSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace distance_converter
{
template <class ContainerAllocator>
struct motorStatusResponse_
{
  typedef motorStatusResponse_<ContainerAllocator> Type;

  motorStatusResponse_()
    : status()  {
    }
  motorStatusResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::distance_converter::motorStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distance_converter::motorStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct motorStatusResponse_

typedef ::distance_converter::motorStatusResponse_<std::allocator<void> > motorStatusResponse;

typedef boost::shared_ptr< ::distance_converter::motorStatusResponse > motorStatusResponsePtr;
typedef boost::shared_ptr< ::distance_converter::motorStatusResponse const> motorStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distance_converter::motorStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distance_converter::motorStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distance_converter::motorStatusResponse_<ContainerAllocator1> & lhs, const ::distance_converter::motorStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distance_converter::motorStatusResponse_<ContainerAllocator1> & lhs, const ::distance_converter::motorStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distance_converter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distance_converter::motorStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_converter::motorStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_converter::motorStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::distance_converter::motorStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distance_converter/motorStatusResponse";
  }

  static const char* value(const ::distance_converter::motorStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"\n"
;
  }

  static const char* value(const ::distance_converter::motorStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distance_converter::motorStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distance_converter::motorStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTANCE_CONVERTER_MESSAGE_MOTORSTATUSRESPONSE_H
