// Generated by gencpp from file diagnose_arm/MotorStatus.msg
// DO NOT EDIT!


#ifndef DIAGNOSE_ARM_MESSAGE_MOTORSTATUS_H
#define DIAGNOSE_ARM_MESSAGE_MOTORSTATUS_H

#include <ros/service_traits.h>


#include <diagnose_arm/MotorStatusRequest.h>
#include <diagnose_arm/MotorStatusResponse.h>


namespace diagnose_arm
{

struct MotorStatus
{

typedef MotorStatusRequest Request;
typedef MotorStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorStatus
} // namespace diagnose_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::diagnose_arm::MotorStatus > {
  static const char* value()
  {
    return "3a0ea3b451699c4d47e8566fa83c9fa2";
  }

  static const char* value(const ::diagnose_arm::MotorStatus&) { return value(); }
};

template<>
struct DataType< ::diagnose_arm::MotorStatus > {
  static const char* value()
  {
    return "diagnose_arm/MotorStatus";
  }

  static const char* value(const ::diagnose_arm::MotorStatus&) { return value(); }
};


// service_traits::MD5Sum< ::diagnose_arm::MotorStatusRequest> should match
// service_traits::MD5Sum< ::diagnose_arm::MotorStatus >
template<>
struct MD5Sum< ::diagnose_arm::MotorStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::diagnose_arm::MotorStatus >::value();
  }
  static const char* value(const ::diagnose_arm::MotorStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::diagnose_arm::MotorStatusRequest> should match
// service_traits::DataType< ::diagnose_arm::MotorStatus >
template<>
struct DataType< ::diagnose_arm::MotorStatusRequest>
{
  static const char* value()
  {
    return DataType< ::diagnose_arm::MotorStatus >::value();
  }
  static const char* value(const ::diagnose_arm::MotorStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::diagnose_arm::MotorStatusResponse> should match
// service_traits::MD5Sum< ::diagnose_arm::MotorStatus >
template<>
struct MD5Sum< ::diagnose_arm::MotorStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::diagnose_arm::MotorStatus >::value();
  }
  static const char* value(const ::diagnose_arm::MotorStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::diagnose_arm::MotorStatusResponse> should match
// service_traits::DataType< ::diagnose_arm::MotorStatus >
template<>
struct DataType< ::diagnose_arm::MotorStatusResponse>
{
  static const char* value()
  {
    return DataType< ::diagnose_arm::MotorStatus >::value();
  }
  static const char* value(const ::diagnose_arm::MotorStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIAGNOSE_ARM_MESSAGE_MOTORSTATUS_H
