// Generated by gencpp from file diagnose_arm/MotorStatusResponse.msg
// DO NOT EDIT!


#ifndef DIAGNOSE_ARM_MESSAGE_MOTORSTATUSRESPONSE_H
#define DIAGNOSE_ARM_MESSAGE_MOTORSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diagnose_arm
{
template <class ContainerAllocator>
struct MotorStatusResponse_
{
  typedef MotorStatusResponse_<ContainerAllocator> Type;

  MotorStatusResponse_()
    : message()  {
    }
  MotorStatusResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStatusResponse_

typedef ::diagnose_arm::MotorStatusResponse_<std::allocator<void> > MotorStatusResponse;

typedef boost::shared_ptr< ::diagnose_arm::MotorStatusResponse > MotorStatusResponsePtr;
typedef boost::shared_ptr< ::diagnose_arm::MotorStatusResponse const> MotorStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator1> & lhs, const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator1> & lhs, const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diagnose_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diagnose_arm/MotorStatusResponse";
  }

  static const char* value(const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"\n"
;
  }

  static const char* value(const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diagnose_arm::MotorStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diagnose_arm::MotorStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIAGNOSE_ARM_MESSAGE_MOTORSTATUSRESPONSE_H
