// Generated by gencpp from file diagnose_arm/MotorStatusRequest.msg
// DO NOT EDIT!


#ifndef DIAGNOSE_ARM_MESSAGE_MOTORSTATUSREQUEST_H
#define DIAGNOSE_ARM_MESSAGE_MOTORSTATUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diagnose_arm
{
template <class ContainerAllocator>
struct MotorStatusRequest_
{
  typedef MotorStatusRequest_<ContainerAllocator> Type;

  MotorStatusRequest_()
    : status(false)  {
    }
  MotorStatusRequest_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStatusRequest_

typedef ::diagnose_arm::MotorStatusRequest_<std::allocator<void> > MotorStatusRequest;

typedef boost::shared_ptr< ::diagnose_arm::MotorStatusRequest > MotorStatusRequestPtr;
typedef boost::shared_ptr< ::diagnose_arm::MotorStatusRequest const> MotorStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator1> & lhs, const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator1> & lhs, const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diagnose_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diagnose_arm/MotorStatusRequest";
  }

  static const char* value(const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diagnose_arm::MotorStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diagnose_arm::MotorStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIAGNOSE_ARM_MESSAGE_MOTORSTATUSREQUEST_H
